/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * emply.java
 *
 * Created on Feb 26, 2014, 10:10:01 AM
 */

package operation;
import java.sql.*;
import javax.swing.*;
import java.util.*;
import java.awt.*;
/**
 *
 * @author UnKnown
 */
public class emply extends javax.swing.JFrame {

    /** Creates new form emply */
    public emply() {
        initComponents();
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel1.setText("empno");

        jLabel2.setText("name");

        jLabel3.setText("salary");

        jLabel4.setText("job");

        jButton1.setText("insertion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("deletion");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("showTable");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton1)
                        .addGap(28, 28, 28)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

       // jTextField2.getText// TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int a,b;
        Connection con=null;
PreparedStatement pstm=null;
ResultSet rs=null;
try
{
    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
    con=DriverManager.getConnection("jdbc:odbc:vi7","sheelu","sheelu");

    System.out.println("eeee");
   pstm= con.prepareStatement("insert into emp7(empno,name,salary,job) values(?,?,?,?)");
   boolean c=true;
    while(c)
    {
        a=Integer.parseInt(jTextField1.getText());
        pstm.setInt(1, a);
        pstm.setString(2, jTextField2.getText());
        b=Integer.parseInt(jTextField3.getText());
        pstm.setInt(3, b);
        pstm.setString(4, jTextField4.getText());
        pstm.executeUpdate();
        c=false;
         JOptionPane.showMessageDialog(null,"record are inserted successfuly");

    }

}
catch(Exception e)
{
    System.out.println(e);
}
try
{
    con.close();
}catch(Exception e)
{
System.out.println(e);
}
jTextField1.getText();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
int a,b;
        Connection con=null;
PreparedStatement pstm=null;
ResultSet rs=null;
try
{
    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
    con=DriverManager.getConnection("jdbc:odbc:vi7","sheelu","sheelu");

    System.out.println("eeee");
   pstm= con.prepareStatement("delete from emp7 where empno=?");
   boolean c=true;
    while(c)
    {
        a=Integer.parseInt(jTextField1.getText());
        pstm.setInt(1, a);
       int count= pstm.executeUpdate();
       if(count>0)
           JOptionPane.showMessageDialog(null,"record are deleted successfuly");
        
       else
           JOptionPane.showMessageDialog(null,"no such record are found");
         
        c=false;

    }

}
catch(Exception e)
{
    System.out.println(e);
}
try
{
    con.close();
}catch(Exception e)
{
System.out.println(e);
}
jTextField1.getText();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      int a,b;
               Connection con=null;
PreparedStatement pstm=null;
ResultSet rs=null;
String y;
try
{
    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
    con=DriverManager.getConnection("jdbc:odbc:vi7","sheelu","sheelu");

    System.out.println("eeee");
   pstm= con.prepareStatement("select * from emp7 where empno=?");
   boolean c=true;
   int count=0;
   while(c)
   {
        a=Integer.parseInt(jTextField1.getText());

       pstm.setInt(1, Integer.parseInt(jTextField1.getText()));

   rs= pstm.executeQuery();
    while(rs.next())
    {
        jTextField2.setText(rs.getString(2));
        jTextField3.setText(Integer.toString(rs.getInt(3)));
        jTextField4.setText(rs.getString(4));
        count++;
    }
       
       
       if(count==0)
          JOptionPane.showMessageDialog(null,"no such empno is found");
       else
            JOptionPane.showMessageDialog(null,"record are search successfuly");

        c=false;

    }

}
catch(Exception e)
{
    System.out.println(e);
}
try
{
    con.close();
}catch(Exception e)
{
System.out.println(e);
}
jTextField1.getText();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     int a,b,g;
        Connection con=null;
PreparedStatement pstm=null;
ResultSet rs=null;
try
{
    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
    con=DriverManager.getConnection("jdbc:odbc:vi7","sheelu","sheelu");

    System.out.println("eeee");
    g=Integer.parseInt(jTextField1.getText());
    String l=jTextField2.getText();
    int m=Integer.parseInt(jTextField3.getText());
  String n=jTextField4.getText();
//String ss="update emp7 set name=?,salary=?,job=? where empno=? ";
   pstm= con.prepareStatement("update emp7 set name=?,salary=?,job=? where empno=? ");
int count=0;
   boolean c=true;
    while(c)
    {
   pstm.setInt(4,g);
pstm.setString(1, jTextField2.getText());
pstm.setInt(2, Integer.parseInt(jTextField3.getText()));
pstm.setString(3, jTextField4.getText());
 


     count=pstm.executeUpdate();
        
       if(count>0)
           JOptionPane.showMessageDialog(null,"record are updated successfuly");
       else
           JOptionPane.showMessageDialog(null,"no such empno is found");
        
        c=false;

    }

}
catch(Exception e)
{
    System.out.println(e);
}
try
{
    con.close();
}catch(Exception e)
{
System.out.println(e);
}
jTextField1.getText();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
Vector rows=new Vector();
Vector cols=new Vector();
JTable table;
Connection con=null;
Statement st=null;
ResultSet rs=null;
ResultSetMetaData rsmd=null;
Container c=getContentPane();
try
{
    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
    con=DriverManager.getConnection("jdbc:odbc:viju","sheelu","sheelu");
    st=con.createStatement();
    rs=st.executeQuery("select * from emp7");
    rsmd=rs.getMetaData();
    int cs=rsmd.getColumnCount();
    for(int i=1;i<=cs;i++)
    {
        cols.add(rsmd.getColumnName(i));
    }
    rows.add(cols);
        while(rs.next())
        {
            Vector temp=new Vector();
            for(int i=1;i<=cs;i++)
            {
                temp.add(rs.getString(i));
            }
            rows.add(temp);
        }
    table =new JTable(rows,cols);
    JOptionPane.showMessageDialog(null,table,"table emp7",JOptionPane.INFORMATION_MESSAGE);
    }
catch(Exception e)
{
    System.out.println(e);

}
setSize(400,400);
setLocation(50,50);
show();
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new emply().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

}
